### ISSUE TITLE
Requirements.txt installation issue

### ISSUE THREAD

**Issue by ProgramerAnel** [rayed/django_crud#3]
Which part am i missing when try to install requirements ?

> 
> Collecting Django<2.2,>=2.1.2 (from -r requirements.txt (line 1))
>   Could not find a version that satisfies the requirement Django<2.2,>=2.1.2 (from -r requirements.txt (line 1)) (from versions: 1.1.3, 1.1.4, 1.2
> , 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1
> .4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5
> .2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1
> .6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2,
>  1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.
> 9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1
> .10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11
> .7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16)
> No matching distribution found for Django<2.2,>=2.1.2 (from -r requirements.txt (line 1))

**Comment by bittner** [comment]
You're probably running Python 2.7, while Django >= 2 requires Python 3. Make sure you use Python 3, e.g.

```bash
$ python3 - m pip install - r requirements.txt
```

**Comment by bittner** [comment]
Oh, I see: The problem is caused by the way you run `manage.py` and the way `manage.py` is configured to use a default python executable:

```cmd
 C:\Users\t3cho\Desktop\tmp.folder\django_crud> manage.py migrate
```
and
```bash
#!/usr/bin/env python
```
in the [first line of manage.py](https://github.com/rayed/django_crud/blob/master/manage.py#L1) results in something that is equivalent to this:
```cmd
 C:\Users\t3cho\Desktop\tmp.folder\django_crud> python manage.py migrate
```
But what you want is _this_:
```cmd
 C:\Users\t3cho\Desktop\tmp.folder\django_crud> py manage.py migrate
```

Side Comment
-----------
I don't know why `py` is the Python executable of your Python 3.7 installation, but heck, that's Windows. (Microsoft has a track record of making things difficult for programmers. Okay, I'm exaggerating. :smirk:)

Still interesting, though, that Windows seems to evaluate [hash bangs](https://en.wikipedia.org/wiki/Shebang_(Unix)) in script files.

Workaround Solution
------------------
I'm afraid, the solution for _you_ is running `py manage.py`. Said that, ...

Suggested Bugfix
---------------
... the solution (for everyone _else_) is changing line 1 in `manage.py` to:
```bash
#!/usr/bin/env python3
```

**Comment by ProgramerAnel** [comment]
Suggested Bugfix solved the issue.

Thanks

**Comment by rayed** [comment]
`manage.py` is auto generated from `django-admin startproject` command, I don't recommend modifying it.

It is better to setup a Python Virtual Environment, this way `python` command would point to the proper version, and it would allow you to install different version of Django or other Python packages.

I haven't work in Windows for ages, but I think you would find this article useful:

https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-windows-10#step-5-%E2%80%94-setting-up-a-virtual-environment
